---
# log_level: "INFO"

# poll_rate: 5 # Poll rate in minutes 

oura_personal_access_token: 

# elasticsearch:

    # cloud_id: ""

    # Elasticsearch URL
    # host: "https://localhost:9200"
    
    # ca_certs: "ca.crt"
    # verify_certs: False

    # HTTP Authentication
    # username:  elastic
    # password: password

    # API authentication
    # api_id: "Zg2WK38B9J4RUZWBWqpr"
    # api_key: "tfs5l3WAShmeeYLl4SBQSg"
    
    # Oura stats index 
    # index: 
